services:
  nest_boilerplate_api:
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/usr/src/nest/apps/api/src:cached
      - ./apps/redis/src:/usr/src/nest/apps/redis/src:cached
      - ./tsconfig.json:/usr/src/nest/tsconfig.json
      - ./package.json:/usr/src/nest/package.json
      - ./yarn.lock:/usr/src/nest/yarn.lock
      - /usr/src/nest/node_modules
    environment:
      NODE_ENV: development
