FROM node:22-alpine

WORKDIR /usr/src/nest

COPY package*.json ./
RUN yarn install --production --silent

COPY . .

RUN npx prisma generate
RUN yarn build
RUN rm -rf src

RUN chmod +x scripts/*.sh

EXPOSE 3001

ENTRYPOINT ["scripts/wait-for-it.sh", "nest_boilerplate_mysql", "3306", "--"]
CMD ["scripts/start-prod.sh"]
